# Generated by Django 4.0.3 on 2022-05-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_remove_article_author_remove_article_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
